apps-$(CONFIG_APP_UXAS_PROCESSOR) += uxas_processor
uxas_processor: common libsel4 libmuslc libsel4vka libsel4allocman libsel4muslcsys \
libsel4vspace libsel4utils libpci libcpio libsel4vmm libelf libutils libsel4camkes libsel4sync \
libsel4debug libsel4muslccamkes libsel4simple libsel4simple-default libsel4platsupport libethdrivers liblwip