#ifndef __tb_AADL_TaskServiceBase_types__H
#define __tb_AADL_TaskServiceBase_types__H

#include <tb_uxas_processor_types.h>

bool tb_CreateNewService_in_dequeue(UXNATIVE__CreateNewService_i * tb_CreateNewService_in);
bool tb_GroundVehicleConfiguration_in_dequeue(IMPACT__GroundVehicleConfiguration_i * tb_GroundVehicleConfiguration_in);
bool tb_EntityConfiguration_in_dequeue(CMASI__EntityConfiguration_i * tb_EntityConfiguration_in);
bool tb_SurfaceVehicleConfiguration_in_dequeue(IMPACT__SurfaceVehicleConfiguration_i * tb_SurfaceVehicleConfiguration_in);
bool tb_AirVehicleConfiguration_in_dequeue(CMASI__AirVehicleConfiguration_i * tb_AirVehicleConfiguration_in);
bool tb_EntityState_in_dequeue(CMASI__EntityState_i * tb_EntityState_in);
bool tb_TaskImplementationRequest_in_dequeue(UXTASK__TaskImplementationRequest_i * tb_TaskImplementationRequest_in);
bool tb_GroundVehicleState_in_dequeue(IMPACT__GroundVehicleState_i * tb_GroundVehicleState_in);
bool tb_UniqueAutomationRequest_in_dequeue(UXTASK__UniqueAutomationRequest_i * tb_UniqueAutomationRequest_in);
bool tb_UniqueAutomationResponse_in_dequeue(UXTASK__UniqueAutomationResponse_i * tb_UniqueAutomationResponse_in);
bool tb_SurfaceVehicleState_in_dequeue(IMPACT__SurfaceVehicleState_i * tb_SurfaceVehicleState_in);
bool tb_AirVehicleState_in_dequeue(CMASI__AirVehicleState_i * tb_AirVehicleState_in);
bool tb_TaskInitialized_out_enqueue(const UXTASK__TaskInitialized_i * tb_TaskInitialized_out);
bool tb_TaskActive_out_enqueue(const UXTASK__TaskActive_i * tb_TaskActive_out);
bool tb_TaskImplementationResponse_out_enqueue(const UXTASK__TaskImplementationResponse_i * tb_TaskImplementationResponse_out);
bool tb_TaskComplete_out_enqueue(const UXTASK__TaskComplete_i * tb_TaskComplete_out);
bool tb_TaskPlanOptions_out_enqueue(const UXTASK__TaskPlanOptions_i * tb_TaskPlanOptions_out);
bool tb_SensorFootprintRequests_out_enqueue(const UXTASK__SensorFootprintRequests_i * tb_SensorFootprintRequests_out);
bool tb_SensorFootprintResponse_in_dequeue(UXTASK__SensorFootprintResponse_i * tb_SensorFootprintResponse_in);
bool tb_VehicleActionCommand_out_enqueue(const CMASI__VehicleActionCommand_i * tb_VehicleActionCommand_out);
bool tb_RouteRequest_out_enqueue(const ROUTE__RouteRequest_i * tb_RouteRequest_out);
bool tb_RouteResponse_in_dequeue(ROUTE__RouteResponse_i * tb_RouteResponse_in);

#endif // __tb_AADL_TaskServiceBase_types__H
