#ifndef __tb_AADL_WaypointPlanManagerService_types__H
#define __tb_AADL_WaypointPlanManagerService_types__H

#include <tb_uxas_processor_types.h>

bool tb_MissionCommand_in_dequeue(CMASI__MissionCommand_i * tb_MissionCommand_in);
bool tb_AirVehicleState_in_dequeue(CMASI__AirVehicleState_i * tb_AirVehicleState_in);
bool tb_IncrementWaypoint_in_dequeue(UXNATIVE__IncrementWaypoint_i * tb_IncrementWaypoint_in);
bool tb_AutomationResponse_in_dequeue(CMASI__AutomationResponse_i * tb_AutomationResponse_in);

#endif // __tb_AADL_WaypointPlanManagerService_types__H
